package com.ghostben.mybatis.mybatis_generator.dao;

import com.ghostben.mybatis.mybatis_generator.entity.PersonEntity;

public interface PersonEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    int deleteByPrimaryKey(Integer personid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    int insert(PersonEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    int insertSelective(PersonEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    PersonEntity selectByPrimaryKey(Integer personid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    int updateByPrimaryKeySelective(PersonEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    int updateByPrimaryKey(PersonEntity record);
}