package com.ghostben.mybatis.mybatis_generator.entity;

import java.io.Serializable;

public class PersonEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.personid
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    private Integer personid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.personname
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    private String personname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.personage
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    private Integer personage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.personid
     *
     * @return the value of person.personid
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    public Integer getPersonid() {
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.personid
     *
     * @param personid the value for person.personid
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    public void setPersonid(Integer personid) {
        this.personid = personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.personname
     *
     * @return the value of person.personname
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    public String getPersonname() {
        return personname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.personname
     *
     * @param personname the value for person.personname
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    public void setPersonname(String personname) {
        this.personname = personname == null ? null : personname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.personage
     *
     * @return the value of person.personage
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    public Integer getPersonage() {
        return personage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.personage
     *
     * @param personage the value for person.personage
     *
     * @mbg.generated Tue Aug 07 14:34:41 CST 2018
     */
    public void setPersonage(Integer personage) {
        this.personage = personage;
    }
}